title : Hanson's Blog
tagline: fantastic{}
author :
  name : Hanson Yu
  email : hangzhong.yu@gemail.com
  github : 2hanson
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - about.md
  
